version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - docker/install-docker
      - run:
          name: Build Docker image
          command: |
            docker build --build-arg NPM_ARGS="--save-dev @babel/plugin-transform-modules-commonjs" -t smartinternship:latest .
      - run:
          name: Docker login
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Tag Docker image with 1.0.0
          command: |
            docker tag smartinternship:latest $DOCKERHUB_USERNAME/smartinternship:1.0.0
      - run:
          name: Push Docker image with tag 1.0.0
          command: |
            docker push $DOCKERHUB_USERNAME/smartinternship:1.0.0
      - run:
          name: Pull latest image from DockerHub and run tests
          command: |
            docker pull $DOCKERHUB_USERNAME/smartinternship:latest
            docker run $DOCKERHUB_USERNAME/smartinternship:latest npm run test:middleware

workflows:
  build-test-push:
    jobs:
      - build-and-test:
          context:
            - docker-hub-credentials
